name: Stall POS Extensions

on:
  push:
    branches:
      - main
    paths:
      - "extensions/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies at root
        run: bun install

      - name: Run tests at root
        run: bun test || echo "No tests found"

  deploy-to-r2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Build, version check, and upload changed extensions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        run: |
          set -e

          # Construct the R2 S3-compatible endpoint URL
          ENDPOINT_URL="https://${CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com"

          CHANGED_EXTENSIONS=$(git diff --name-only HEAD~1 HEAD | grep '^extensions/' | awk -F'/' '{print $1 "/" $2}' | uniq)

          if [ -z "$CHANGED_EXTENSIONS" ]; then
            echo "No extensions were changed. Nothing to deploy."
            exit 0
          fi

          echo "🚀 Found changed extensions to deploy:"
          echo "$CHANGED_EXTENSIONS"

          for ext_dir in $CHANGED_EXTENSIONS; do
            if [ -f "$ext_dir/package.json" ]; then
              echo "📦 Processing: $ext_dir"
              (
                cd "$ext_dir"

                pkg_name=$(jq -r '.name | sub("@stallpos/"; "")' package.json)
                pkg_version=$(jq -r '.version' package.json)
                R2_OBJECT_KEY="${pkg_name}/${pkg_version}/index.js"

                echo "Checking if version ${pkg_version} already exists at ${R2_OBJECT_KEY}..."

                # Check existence using AWS CLI (head-object returns 0 if exists, non-zero if not)
                if aws s3api head-object --bucket "${R2_BUCKET_NAME}" --key "${R2_OBJECT_KEY}" --endpoint-url "${ENDPOINT_URL}" > /dev/null 2>&1; then
                  echo "❌ Error: Version ${pkg_version} of ${pkg_name} already exists in R2. Please increment the version number."
                  exit 1
                else
                  echo "✅ Version does not exist. Proceeding..."
                fi

                echo "Installing dependencies..."
                bun install

                echo "Building asset..."
                bun run build || echo "⚠️ No build script or build failed"

                SOURCE_FILE="dist/index.js"
                if [ ! -f "$SOURCE_FILE" ]; then
                  echo "❌ Build artifact not found at $SOURCE_FILE."
                  exit 1
                fi

                echo "Uploading ${SOURCE_FILE} to R2 bucket '${R2_BUCKET_NAME}' as '${R2_OBJECT_KEY}'..."
                aws s3 cp "${SOURCE_FILE}" "s3://${R2_BUCKET_NAME}/${R2_OBJECT_KEY}" --endpoint-url "${ENDPOINT_URL}" --content-type "application/javascript"

                echo "✅ Successfully uploaded ${pkg_name}@${pkg_version}."
              )
            fi
          done
